/**
 * Stable, client-facing error codes. The frontend maps each one to a translated
 * message (`frontend/src/common/locales/<lang>/errors.json`), so a code must never
 * be renamed once shipped — add a new one instead.
 */
export const ERROR_CODES = {
  // Generic
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  RATE_LIMITED: 'RATE_LIMITED',
  UPSTREAM_UNAVAILABLE: 'UPSTREAM_UNAVAILABLE',
  CONFIGURATION_ERROR: 'CONFIGURATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Auth
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  PASSWORD_TOO_WEAK: 'PASSWORD_TOO_WEAK',
  TOKEN_INVALID: 'TOKEN_INVALID',

  // AI providers
  LLM_NOT_CONFIGURED: 'LLM_NOT_CONFIGURED',
  LLM_UNAVAILABLE: 'LLM_UNAVAILABLE',
  LLM_BUDGET_EXHAUSTED: 'LLM_BUDGET_EXHAUSTED',

  // Files
  FILE_INVALID: 'FILE_INVALID',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',

  // Resumes
  RESUME_NOT_FOUND: 'RESUME_NOT_FOUND',
  RESUME_TEXT_EMPTY: 'RESUME_TEXT_EMPTY',
  RESUME_TOO_LONG: 'RESUME_TOO_LONG',
  RESUME_LIMIT_REACHED: 'RESUME_LIMIT_REACHED',
  RESUME_NOT_PARSED: 'RESUME_NOT_PARSED',
  RESUME_PARSE_IN_PROGRESS: 'RESUME_PARSE_IN_PROGRESS',
  RESUME_HAS_EDITS: 'RESUME_HAS_EDITS',
  TEMPLATE_NOT_FOUND: 'TEMPLATE_NOT_FOUND',

  // Jobs
  PROFILE_INCOMPLETE: 'PROFILE_INCOMPLETE',
  JOB_NOT_FOUND: 'JOB_NOT_FOUND',
  JOB_SOURCE_UNKNOWN: 'JOB_SOURCE_UNKNOWN',
  JOB_SCORING_IN_PROGRESS: 'JOB_SCORING_IN_PROGRESS',
  DISCOVERY_TOO_SOON: 'DISCOVERY_TOO_SOON',

  // Applications and tailoring
  APPLICATION_NOT_FOUND: 'APPLICATION_NOT_FOUND',
  APPLICATION_CHANGED: 'APPLICATION_CHANGED',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  TAILOR_IN_PROGRESS: 'TAILOR_IN_PROGRESS',
  TAILOR_DAILY_CAP_REACHED: 'TAILOR_DAILY_CAP_REACHED',
  VARIANT_NOT_FOUND: 'VARIANT_NOT_FOUND',
  RESUME_TAILOR_FACT_VIOLATION: 'RESUME_TAILOR_FACT_VIOLATION',
  RESUME_VARIANT_NOT_APPROVED: 'RESUME_VARIANT_NOT_APPROVED',

  // Hiring posts and contacts
  HIRING_QUERY_INVALID: 'HIRING_QUERY_INVALID',
  HIRING_POST_NOT_FOUND: 'HIRING_POST_NOT_FOUND',
  CONTACT_NOT_FOUND: 'CONTACT_NOT_FOUND',
  CONTACT_EXISTS: 'CONTACT_EXISTS',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
