import { BindingScope, injectable } from '@loopback/core';
import { promises as fs } from 'fs';
import path from 'path';
import { envString } from '../../common/config/env.util';
import { AppNotFoundError, AppValidationError, ERROR_CODES } from '../../common/errors';

const SAFE_KEY = /^[A-Za-z0-9][A-Za-z0-9._\-/]*$/;

/**
 * Private file storage on local disk under STORAGE_DIR. Keys are generated by
 * the server (`<userId>/<kind>/<uuid>.<ext>`), never taken from a client, and
 * are validated so a key can never escape the root.
 */
@injectable({ scope: BindingScope.SINGLETON })
export class StorageService {
  root(): string {
    return path.resolve(envString('STORAGE_DIR', path.join(process.cwd(), 'storage'))!);
  }

  async put(key: string, data: Buffer): Promise<void> {
    const target = this.resolve(key);
    await fs.mkdir(path.dirname(target), { recursive: true });
    await fs.writeFile(target, data);
  }

  async get(key: string): Promise<Buffer> {
    try {
      return await fs.readFile(this.resolve(key));
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') throw new AppNotFoundError(ERROR_CODES.FILE_NOT_FOUND, 'File not found');
      throw error;
    }
  }

  async delete(key: string): Promise<void> {
    await fs.rm(this.resolve(key), { force: true });
  }

  private resolve(key: string): string {
    if (!SAFE_KEY.test(key) || key.includes('..')) {
      throw new AppValidationError(ERROR_CODES.VALIDATION_ERROR, 'Invalid storage key');
    }
    const root = this.root();
    const target = path.resolve(root, key);
    if (!target.startsWith(root + path.sep)) throw new AppValidationError(ERROR_CODES.VALIDATION_ERROR, 'Invalid storage key');
    return target;
  }
}
